export interface MailerCheckResponseBody {
    referenceId: string,
    firstName: string,
    middleInitial: string,
    lastName: string,
    suffix: string,
    address: string,
    city: string,
    stateAbbreviation: string,
    zip: string,
    crrt: string,
    barcode: string,
    county: string,
    estimatedDebt: number,
    settled: number,
    newPayment: number,
    tier: string,
    segment: string,
    drop: string,
    tollFreeNumber: string,
    spanishTollFreeNumber: string,
    noticeDate: string,
    url: string,
    stateFull: string,
};
